addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"          % "1.6.0")
addSbtPlugin("org.scoverage"  % "sbt-coveralls"          % "1.2.7")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"           % "2.5")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"                % "1.1.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.0.3")
